server:
  port: 8030

spring:
  datasource:
    url: jdbc:mysql://localhost:23306/test
    username: root
    password: ibjang123
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
#        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: create
    open-in-view: off
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 10000ms
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer